### ISSUE TITLE
Ability to define test name prefix for documentation page

### ISSUE THREAD

**Issue by nikitinas** [devcrocod/korro#1]
The most maintainable way to use 'korro' - to have one test file per one documentation file.

Therefore it's reasonable to have an ability to define test name prefix once and use short test names instead of fully qualified.
This will also help with package structure refactorings.

Usage example:

**doc.md**
```
<!---TESTS docs.api.TestClass-->
...
<!---test1-->
<!---END-->
```
**test.kt**
```
package docs.api
class TestClass {

  fun test1() {
    ...
    // SampleStart
    sample code
    // SampleEnd
    ...
  }
}
```

**Comment by devcrocod** [comment]
I was thinking about adding imports to documentation, then it would be possible to add more than one test class.

**Comment by nikitinas** [comment]
Yes, that's even better approach:
`<!---IMPORT docs.api.TestClass-->`
