### ISSUE TITLE
Update Dokka to 1.9.10?

### ISSUE THREAD

**Issue by Jolanrensen** [devcrocod/korro#8]
![image](https://github.com/devcrocod/korro/assets/17594275/be16acba-1cfb-4875-a7fb-9839d684ff5d)

Looks like Korro ships with Dokka 1.8.10 while v1.9.10 is already [released](https://central.sonatype.com/search?q=org.jetbrains.dokka&sort=published). 

As Korro is used as build dependency in DataFrame, we cannot update Dokka to 1.9.10 ourselves:

```
java.lang.NoSuchMethodError: 'org.gradle.api.provider.Property org.jetbrains.dokka.gradle.DokkaTask.getOutputDirectory()'
```

**Comment by devcrocod** [comment]
yes I will update.
 but I don’t really understand how this affects you?  since these dependencies should not affect the dependencies in the project.  so in Kandy we have been using version 1.9.10 of dokka

**Comment by Jolanrensen** [comment]
I'm not sure, but simply using the `korro` plugin with the `dokka` plugin at 1.9.10 gives me that exception. Disabling dokka or downgrading it to 1.8.10 fixes it.

I can't reproduce it in another project either. But it might be because we apply Dokka project-wide and korro only for individual modules?

**Comment by devcrocod** [comment]
@Jolanrensen 
Unfortunately, a simple update is not enough here. Dokka, since 1.9.0, has completely rewritten all the logic responsible for parsing Kdoc and code. As a result, it is necessary to completely rewrite the code on the korro side or write it from scratch, which may even be easier

**Comment by Jolanrensen** [comment]
@devcrocod Okay no hurry then. I'll face the same problem here https://github.com/Jolanrensen/docProcessorGradlePlugin/issues/42, which will also take some time.
